### PR TITLE
Update

### PR DESCRIPTION
**Pull request by knownasilya**
Uses new Ember import APIs and testing APIs so this can be used with Ember 3.4

### CODE REVIEW

**Comment by knownasilya** [comment]
Might be a nice time to release a 1.0

**Comment by knownasilya** [comment]
Tests should pass now, giving it a few minutes

**Comment by knownasilya** [comment]
@runspired think this could get merged?

**Comment by knownasilya** [comment]
Note to self: don't delete this till a release is out.

**Comment by runspired** [comment]
@knownasilya released

**Pull request merged**
